# Generated by Django 5.0.6 on 2024-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookstoremodel_last_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoremodel',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs'),
        ),
    ]
